fix clang build
Fix weird link error caused by building libquickjs.a with LTO plus gcc,
then linking against it from youtube-unthrottle built with clang:

[ 82%] Linking C executable youtube-unthrottle
/usr/bin/ld: /usr/lib/quickjs/libquickjs.a(quickjs.o): plugin needed to handle lto object
/usr/bin/ld: /usr/lib/quickjs/libquickjs.a(quickjs.o): plugin needed to handle lto object
/usr/bin/ld: libyoutube.a(js.c.o): in function `call_js_foreach':
/builds/ewoo/youtube-unthrottle/src/lib/js.c:427:(.text+0xbdc): undefined reference to `JS_NewRuntime'
/usr/bin/ld: /builds/ewoo/youtube-unthrottle/src/lib/js.c:431:(.text+0xbf0): undefined reference to `JS_NewContext'
/usr/bin/ld: /builds/ewoo/youtube-unthrottle/src/lib/js.c:408:(.text+0xca0): undefined reference to `JS_Eval'
/usr/bin/ld: libyoutube.a(js.c.o): in function `JS_FreeValue':
/usr/include/quickjs/quickjs.h:684:(.text+0xcf5): undefined reference to `__JS_FreeValue'
[...]