fix gcc build
Fix weird link error on libquickjs.a:

/usr/bin/ld: /tmp/ccvwzcfv.ltrans0.ltrans.o: undefined reference to symbol 'exp@@GLIBC_2.29'
/usr/bin/ld: /usr/lib/../lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status